import {
    mdiLogout,
    mdiFolderMultiple,
    mdiChartBox,
    mdiFileDocument,
    mdiMagnify,
    mdiPlus,
    mdiFolderOpenOutline,
    mdiMenuDown,
    mdiCheck,
    mdiDotsVertical,
    mdiChevronLeft,
    mdiChevronRight,
    mdiDownload,
    mdiWindowClose,
    mdiUpload,
    mdiMinus,
    mdiAlert,
    mdiLoading,
    mdiUndo,
    mdiRedo,
    mdiFormatBold,
    mdiFormatItalic,
    mdiFormatUnderline,
    mdiFormatHeader1,
    mdiFormatHeader3,
    mdiFormatHeader2,
    mdiFormatHeader4,
    mdiFormatHeader5,
    mdiFormatHeader6,
    mdiFormatQuoteClose,
    mdiFormatStrikethroughVariant,
    mdiFormatColorHighlight,
    mdiFormatAlignJustify,
    mdiFormatAlignCenter,
    mdiFormatAlignLeft,
    mdiFormatAlignRight,
    mdiFormatListBulleted,
    mdiFormatListNumbered,
    mdiTable,
    mdiCommentOutline,
    mdiCodeBlockTags,
    mdiFormatParagraph,
    mdiBell,
    mdiCog,
    mdiClock,
    mdiSquare,
    mdiFolder, mdiDrawingBox, mdiCircle, mdiFilter, mdiGrid
} from "@mdi/js"

const ICON_PATHS = {
    LOGOUT: mdiLogout,
    FOLDER_COPY: mdiFolderMultiple,
    ANALYSIS: mdiChartBox,
    DESCRIPTION: mdiFileDocument,
    SEARCH: mdiMagnify,
    FILTER: mdiFilter,
    GRID: mdiGrid,
    CLOCK: mdiClock,
    ADD: mdiPlus ,
    OPEN_FOLDER: mdiFolderOpenOutline,
    FOLDER: mdiFolder,
    ARROW_DROP_DOWN: mdiMenuDown ,
    DONE: mdiCheck ,
    BELL: mdiBell,
    CIRCLE: mdiCircle,
    SQUARE: mdiSquare,
    BOX: mdiDrawingBox,
    CHECK: mdiCheck,
    SETTINGS: mdiCog,
    MORE_VERT: mdiDotsVertical ,
    KEYBOARD_ARROW_LEFT: mdiChevronLeft ,
    KEYBOARD_ARROW_RIGHT: mdiChevronRight,
    DOWNLOAD: mdiDownload ,
    PROGRESS_ACTIVITY: mdiLoading ,
    CROSS: mdiWindowClose ,
    UPLOAD: mdiUpload ,
    REMOVE: mdiMinus ,
    WARNING: mdiAlert ,
    UNDO: mdiUndo,
    REDO: mdiRedo,
    FORMAT_BOLD: mdiFormatBold,
    FORMAT_ITALIC: mdiFormatItalic,
    FORMAT_STRIKETHROUGH: mdiFormatStrikethroughVariant,
    FORMAT_UNDERLINE: mdiFormatUnderline,
    FORMAT_HEADER_1: mdiFormatHeader1,
    FORMAT_HEADER_2: mdiFormatHeader2,
    FORMAT_HEADER_3: mdiFormatHeader3,
    FORMAT_HEADER_4: mdiFormatHeader4,
    FORMAT_HEADER_5: mdiFormatHeader5,
    FORMAT_HEADER_6: mdiFormatHeader6,
    FORMAT_ALIGN_CENTER: mdiFormatAlignCenter,
    FORMAT_ALIGN_LEFT: mdiFormatAlignLeft,
    FORMAT_ALIGN_RIGHT: mdiFormatAlignRight,
    FORMAT_ALIGN_JUSTIFY: mdiFormatAlignJustify,
    FORMAT_QUOTE: mdiFormatQuoteClose,
    FORMAT_HIGHLIGHT: mdiFormatColorHighlight,
    FORMAT_LIST_UNNUMBERED: mdiFormatListBulleted,
    FORMAT_LIST_NUMBERED: mdiFormatListNumbered,
    FORMAT_TABLE: mdiTable,
    COMMENT: mdiCommentOutline,
    FORMAT_CODE: mdiCodeBlockTags,
    FORMAT_PARAGRAPH: mdiFormatParagraph,
    FORMAT_DIVIDER: mdiMinus,
}

export { ICON_PATHS }